### ISSUE TITLE
1.16.2: Wires are not displayed on placement

### ISSUE THREAD

**Issue by Andre601** [saharNooby/lead-wires#2]
When placing wires using the place-tool are the leads not visible.

The plugin will also complain, that you have already clicked on the block, even if you click it for the first time.

![image](https://user-images.githubusercontent.com/11576465/92282769-9957e680-eefe-11ea-8b1b-d28793fd409f.png)

**Comment by saharNooby** [comment]
Issues on 1.16.2 have been fixed in plugin version 1.1.3.
